theme: jekyll-theme-minimal
title: COVID-19 Case and Death Rates in Massachusetts
description: >-
  Visualization of data taken by the DPH and CDC of new COVID-19 cases in the state of Massachusetts as well as nationwide. Trends of COVID cases depending 
  on vaccine product taken, gender, age group, and vaccination status are visualized.<br>
  <br>
  Updated: September 8<sup>th</sup>, 2022
  
